/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package newlibrary;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Font;

/**
 *
 * @author Sandeep
 */
public class Create extends javax.swing.JFrame {

    /**
     * Creates new form Create
     */
    public Create() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FnTF = new javax.swing.JTextField();
        LnTF = new javax.swing.JTextField();
        ATF = new javax.swing.JTextField();
        PTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(Color.LIGHT_GRAY);

        jLabel1.setFont(new Font("Calisto MT", Font.PLAIN, 24)); // NOI18N
        jLabel1.setText("Fill in all your details  ");

        jLabel3.setText("First Name*");

        jLabel4.setText("Last Name*");

        jLabel5.setText("Address*");

        jLabel6.setText("Phone");

        FnTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnTFActionPerformed(evt);
            }
        });
        FnTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FnTFKeyPressed(evt);
            }
        });

        LnTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LnTFKeyPressed(evt);
            }
        });

        ATF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ATFKeyPressed(evt);
            }
        });

        PTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTFActionPerformed(evt);
            }
        });
        PTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PTFKeyPressed(evt);
            }
        });

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back to Main Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8))
                    .addComponent(jButton2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ATF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(PTF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(FnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ATF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(PTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String fname="",lname="",address="",phn="";
        if(FnTF.getText().isEmpty()||LnTF.getText().isEmpty()||ATF.getText().isEmpty())
        {
                jLabel8.setForeground(Color.red);
                jLabel8.setText("First Name,Lname and Address fields are required");
        }
        else 
        {
            if(PTF.getText().isEmpty())
            {
                phn=null;
            }
            else
            {
                if(PTF.getText().length()!= 10)
                {
                    jLabel7.setForeground(Color.red);
                    jLabel7.setText("It is not a valid phone number");
                }
                else
                {
                    jLabel7.setForeground(Color.blue);
                    jLabel7.setText("valid phone number");
                    String area_code=PTF.getText().substring(0,3);
                    String b=PTF.getText().substring(3,6);
                    String c=PTF.getText().substring(6);
                    phn= "("+area_code+") "+b+"-"+c;
                    System.out.println(phn);
                 }
            }
            fname=FnTF.getText();
            lname=LnTF.getText();
            address=ATF.getText();
            try
            {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/", "root", "2934991");
            Statement stmt=conn.createStatement();
            PreparedStatement preparedstatement = null;
            stmt.execute("use library_server;");
            String qry="select * from borrower where fname='"+fname+"' and Lname='"+lname+"' and address='"+address+"';";

            ResultSet rs=stmt.executeQuery(qry);
            if(rs.next())
            {
                jLabel8.setForeground(Color.red);
                jLabel8.setText("There is already a user with same fname,lname,address");
                
            }
            else
            {
                int cn,crd_no=0;
                 
                 qry="select max(card_no) as MAX from borrower; ";
                 rs=stmt.executeQuery(qry);
                 while(rs.next())
                 {
                     crd_no=rs.getInt("MAX");
                     crd_no++;
                 }
                     cn=crd_no;
                    jLabel8.setForeground(Color.blue);
                    jLabel8.setText("all details are correct");
                    System.out.println("The values are"+cn+"\t"+fname+"\t"+lname+"\t"+address+"\t"+phn);
                    
                       int k=createborrower(conn,preparedstatement,cn,fname,lname,address,phn);
                        if(k==1)
                        {
                            JOptionPane.showMessageDialog(null,"Creation Successful"); 
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"some erro in creation","ERROR",JOptionPane.ERROR_MESSAGE);
                        }
                
            }
            
        }
            catch(SQLException e)
            {
                Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, e);
            }
            
        }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    public void close()
    {
    WindowEvent winclosingevent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclosingevent);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          close();
        homepage h=new homepage();
        h.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PTFActionPerformed

    private void FnTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnTFActionPerformed

    private void FnTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FnTFKeyPressed
        // TODO add your handling code here:
        jLabel8.setText("");
        
    }//GEN-LAST:event_FnTFKeyPressed

    private void LnTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LnTFKeyPressed
        // TODO add your handling code here:
        jLabel8.setText("");
    }//GEN-LAST:event_LnTFKeyPressed

    private void ATFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ATFKeyPressed
        // TODO add your handling code here:
        jLabel8.setText("");
    }//GEN-LAST:event_ATFKeyPressed

    private void PTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PTFKeyPressed
        // TODO add your handling code here:
        jLabel7.setText("");
        jLabel8.setText("");
    }//GEN-LAST:event_PTFKeyPressed
  public static int createborrower(Connection connection,PreparedStatement preparedstatement,int cardno,String fn,String ln,String addr,String phn)
   throws SQLException
   {
		    preparedstatement=connection.prepareStatement("insert into borrower(card_no,fname,lname,address,phone) values(?,?,?,?,?)");
		
                    preparedstatement.setInt(1,cardno);
                    preparedstatement.setString(2,fn);
                    preparedstatement.setString(3,ln);
                    preparedstatement.setString(4,addr);
                    preparedstatement.setString(5,phn);
                    
		    int k=preparedstatement.executeUpdate();
                    return k;
   }  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ATF;
    private javax.swing.JTextField FnTF;
    private javax.swing.JTextField LnTF;
    private javax.swing.JTextField PTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
