/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package newlibrary;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;
/**
 *
 * @author Sandeep
 */
public class search extends javax.swing.JFrame {

    /**
     * Creates new form search
     */
    public search() {
        initComponents();
        groupButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Author_NameTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Book_idTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Book_TitleTF = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(Color.LIGHT_GRAY);
        jPanel4.setEnabled(false);

        jLabel6.setText("Book id:");

        Author_NameTF.setEnabled(false);

        jLabel7.setText("Author Name");
        jLabel7.setEnabled(false);

        Book_idTF.setToolTipText("");
        Book_idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_idTFActionPerformed(evt);
            }
        });

        jLabel11.setText("Book Title:");

        jButton5.setText("SEARCH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Chiller", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ENTER ATLEAST ANY ONE SEARCHING CRITERIA ..!!");

        jRadioButton1.setText("Author Name");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Select ur choice:");

        jButton1.setText("Back to Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4Layout.setHorizontalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addGap(37)
        					.addComponent(jLabel7)
        					.addGap(64)
        					.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(Book_idTF, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)
        						.addComponent(Book_TitleTF, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)
        						.addComponent(Author_NameTF, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addGap(133)
        					.addComponent(jButton5))
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addGap(27)
        					.addGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jLabel11, Alignment.LEADING)
        						.addComponent(jLabel6, Alignment.LEADING)))
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel4Layout.createSequentialGroup()
        							.addComponent(jButton1)
        							.addGap(18)
        							.addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 303, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel4Layout.createSequentialGroup()
        							.addComponent(jLabel13)
        							.addGap(70)
        							.addComponent(jRadioButton1)))))
        			.addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(jLabel12))
        			.addGap(34)
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(Book_idTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel6))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel11)
        				.addComponent(Book_TitleTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(55)
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel13)
        				.addComponent(jRadioButton1))
        			.addPreferredGap(ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel7)
        						.addComponent(Author_NameTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(192))
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addComponent(jButton5)
        					.addContainerGap())))
        );
        jPanel4.setLayout(jPanel4Layout);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void groupButton( ) {

ButtonGroup bg1 = new ButtonGroup( );

bg1.add(jRadioButton1);

}

    public static DefaultTableModel buildTableModel(ResultSet rs)
        throws SQLException {

    ResultSetMetaData metaData = rs.getMetaData();

    // names of columns
    Vector<String> columnNames = new Vector<String>();
    int columnCount = metaData.getColumnCount();
    for (int column = 1; column <= columnCount; column++) {
        columnNames.add(metaData.getColumnName(column));
    }

    // data of the table
    Vector<Vector<Object>> data = new Vector<Vector<Object>>();
    while (rs.next()) {
        Vector<Object> vector = new Vector<Object>();
        for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
            vector.add(rs.getObject(columnIndex));
        }
        data.add(vector);
    }

    return new DefaultTableModel(data, columnNames);

}
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/", "root", "2934991");
            Statement stmt=conn.createStatement();
            stmt.execute("use library_server;");
            
            String book_title=null;
            String author_name =null;
            String fname =null;
            String lname =null;
            String mname =null;
            String book_id=null;
            book_id=Book_idTF.getText();
            book_title=Book_TitleTF.getText();
            
            
            if(jRadioButton1.isEnabled()==true)
            {
                author_name=Author_NameTF.getText();
                if(author_name.equalsIgnoreCase(""))
               {
                   author_name = "%";
               }
               
                System.out.println("WE are in Radio button 1 Fname :"+fname+"Lname :"+lname+" Mname :"+mname+"Author Name:"+author_name);
           
               
            } 
         
            /*System.out.println(book_id);
            String qry="SELECT title from book b where b.book_id='"+book_id+"'";
            */
            String query = ""
        +"select total.bookid, total.title, total.author, total.branch_id, total.No_Of_Copies, "
        +"total.No_Of_Copies-coalesce(count(bl.book_id),0) AS Available_copies "   
        + "from book_loans bl right outer join " 
        + "(select books.bookid, books.title, GROUP_CONCAT(ba1.author_name) author, bc.branch_id, bc.No_Of_Copies " 
        + "from book_authors AS ba1, book_copies bc, " 
        + "(select distinct b.Book_id bookid, b.Title title from book AS b, book_authors AS ba where b.Book_id= ba.Book_id and " 
        + "(b.Book_id like '%" + book_id + "%' and b.title like '%" + book_title + "%' and ba.Author_name like '%" + author_name + "%' )) books " 
        + "where ba1.Book_id=books.bookid and bc.Book_id=books.bookid " 
        + "group by books.bookid, books.title, bc.branch_id, bc.No_Of_Copies) total "
        + "on total.bookid=bl.book_id and total.branch_id=bl.Branch_id and bl.Date_in is null "
        + "group by total.bookid, total.title, total.author, total.branch_id,total.No_Of_Copies;";

   
            System.out.println("query =" + query);  
            
        ResultSet rs = stmt.executeQuery(query);
        System.out.println("executed");
       
       JTable table = new JTable(buildTableModel(rs));
       JOptionPane.showMessageDialog(null, new JScrollPane(table));

         
        while (rs.next())
        {
          
            String BookId=rs.getString("bookid");
            String Title=rs.getString("title");
            String Author=rs.getString("author");
            int BranchId=rs.getInt("branch_id");
            int Total_copies=rs.getInt("No_of_copies");
            int Available_copies=rs.getInt("available");
            System.out.println("The values are:"+BookId+"\t"+Title+"\t"+Author+"\t"+BranchId+"\t"+Total_copies+"\t"+Available_copies);
            //jTextArea1.
            }
        
        
        } 
        catch (SQLException ex) {
            Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

        // TODO add your handling code here:
        jLabel7.setEnabled(true);
        Author_NameTF.setEnabled(true);

        
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    public void close()
    {
    WindowEvent winclosingevent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclosingevent);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
        homepage h=new homepage();
        h.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Book_idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_idTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_idTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Author_NameTF;
    private javax.swing.JTextField Book_TitleTF;
    private javax.swing.JTextField Book_idTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables

   
}
